export const MEALS=[['breakfast','Breakfast',.12],['lunch','Lunch',.23],['afternoonSnack','Afternoon snack',.15],['dinner','Dinner',.35],['nightSnack','Night snack',.15]];
export const LABELS={4:['Great','Intentional quality + quantity'],3:['Good','Controlled; one area imperfect'],2:['Drift','Meaningful quality or quantity slip'],1:['Off track','Multiple issues or loss of control'],0:['No snack','A good choice when you are not hungry']};
export const PROGRAM={blue:[['Chest press','3 × 6–10','machine or dumbbell'],['Seated cable row','3 × 8–12',''],['Leg press','3 × 8–12','comfortable range'],['Cable lateral raise','2 × 10–15','superset'],['Cable curl','2 × 8–12','superset'],['Pallof press','2 × 8–12 / side','']],maize:[['Lat pulldown','3 × 8–12',''],['Incline dumbbell press','3 × 6–10',''],['Romanian deadlift','3 × 8–10',''],['Rope triceps pressdown','2 × 8–12','superset'],['Face pull','2 × 10–15','superset'],['Dead bug','2 × 6–10 / side','']],home:[['Incline pushup','2 × 8–12',''],['Glute bridge','2 × 12',''],['Chair squat','2 × 8','only if knees tolerate'],['Bird dog','2 × 8 / side',''],['Prone W raise','2 × 10','']]};
export const initialState=()=>({schemaVersion:1,appVersion:'1.0.0',healthData:{},mealData:{},workouts:{},strengthLogs:[],weightHistory:{},scheduleData:[],simulatedGames:{},athleteProfile:{},xpHistory:[],achievements:[],experiments:{},analyticsResults:{},importedHealthQuestData:{},settings:{onboarded:false,debug:false,trainingBlock:1,program:structuredClone(PROGRAM)}});
export const dateKey=(d=new Date())=>{const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)};
export const weekKey=d=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()-(x.getDay()+6)%7);return dateKey(x)};
export function mealScore(meals){let total=0,weight=0;for(const [key,,w] of MEALS){const v=meals?.[key];if(v===undefined||v===null||v==='')continue;const n=Number(v);const score=key==='nightSnack'?({0:100,4:90,3:75,2:40,1:10})[n]:({4:100,3:82,2:50,1:15})[n];if(score===undefined)continue;total+=w*score;weight+=w}return weight?Math.round(total/weight):null}
export const movementScore=steps=>steps==null?null:Math.round(100*Math.min(1,Math.max(0,Number(steps))/8000));
export function weeklyStrength(state,day){const week=weekKey(day);const types=new Set(Object.entries(state.workouts).filter(([d])=>weekKey(d)===week).map(([,x])=>x));return {gym:Number(types.has('blue'))+Number(types.has('maize')),home:types.has('home'),complete:types.has('blue')&&types.has('maize')}}
export function experiment(state,day){const week=weekKey(day),choice=state.experiments[week]||'steps';const dates=[...new Set([...Object.keys(state.healthData),...Object.keys(state.mealData)])].filter(d=>weekKey(d)===week);let count=0,target=5;for(const d of dates){const m=state.mealData[d]||{},h=state.healthData[d]||{};if(choice==='steps'&&h.steps!=null&&Number(h.steps)>=8000)count++;if(choice==='dinner'&&m.dinner!=null&&Number(m.dinner)>=3)count++;if(choice==='close'&&m.nightSnack===0)count++;if(choice==='breakfast'&&m.breakfast===4)count++}if(choice==='strength'){count=weeklyStrength(state,day).gym;target=2}else if(choice==='steps'||choice==='dinner')target=6;return {choice,count,target,complete:count>=target}}
export function dayXP(state,day){const h=state.healthData[day]||{},m=state.mealData[day]||{},workout=state.workouts[day],score=mealScore(m),ex=experiment(state,day);let xp=0;if(h.weight!=null)xp+=10;if(MEALS.every(([k])=>m[k]!=null))xp+=20;if(Number(h.steps)>=8000)xp+=30;else if(Number(h.steps)>=5000)xp+=20;if(workout==='blue'||workout==='maize')xp+=75;if(workout==='home')xp+=50;if(score!=null&&score>=75)xp+=40;if(comeback(state,day))xp+=40;xp+=Math.round(35*Math.min(1,ex.count/ex.target)/7);return xp}
export function comeback(state,day){const prior=dateKey(new Date(new Date(day+'T12:00:00').getTime()-86400000));const before=state.mealData[prior]||{},now=state.mealData[day]||{};return Object.values(before).some(v=>Number(v)===1)&&mealScore(now)>=75&&Object.values(now).length>=3}
export function totalXP(state){const dates=[...new Set([...Object.keys(state.healthData),...Object.keys(state.mealData),...Object.keys(state.workouts)])];let xp=dates.reduce((n,d)=>n+dayXP(state,d),0);for(const w of new Set(dates.map(weekKey))){const d=dates.find(x=>weekKey(x)===w);if(weeklyStrength(state,d).complete)xp+=100;if(experiment(state,d).complete)xp+=100}return xp+Object.values(state.simulatedGames).length*150}
export function readiness(state,day){const h=state.healthData[day]||{},m=state.mealData[day]||{},n=mealScore(m),move=movementScore(h.steps),strength=weeklyStrength(state,day),ex=experiment(state,day);const recent=Object.keys(state.healthData).filter(d=>d<=day&&d>=dateKey(new Date(new Date(day+'T12:00:00').getTime()-6*86400000)));const consistency=Math.min(100,recent.length*15);return Math.max(0,Math.min(100,Math.round(.34*(n??75)+.25*(move??70)+.2*(strength.gym*42+(strength.home?16:0)+20)+.11*consistency+.1*(50+50*Math.min(1,ex.count/ex.target)))))}
export function attributes(state,day){const r=readiness(state,day),w=weeklyStrength(state,day),m=mealScore(state.mealData[day]),move=movementScore(state.healthData[day]?.steps),ex=experiment(state,day),xp=totalXP(state),base=Math.min(18,Math.floor(xp/650));return {Strength:Math.min(99,48+base+w.gym*6),Conditioning:Math.min(99,48+base+Math.round((move??70)/8)),Discipline:Math.min(99,45+base+Math.round(r/9)),Nutrition:Math.min(99,45+base+Math.round((m??75)/8)),Recovery:Math.min(99,48+base+Math.round((100-Math.max(0,(state.healthData[day]?.steps??0)-12000)/400)/10)),Clutch:Math.min(99,45+base+ex.count*2)}}
export function trend(points,window=7){return points.map((p,i)=>{const values=points.slice(Math.max(0,i-window+1),i+1).map(x=>x.value);return {...p,trend:values.reduce((a,b)=>a+b,0)/values.length}})}
export function allWeights(state){const map=new Map;for(const [d,e] of Object.entries(state.importedHealthQuestData))for(const x of e.normalized||[])if(x.weight!=null)map.set(x.date,x.weight);for(const [d,v] of Object.entries(state.weightHistory))if(v!=null)map.set(d,Number(v));return trend([...map].sort(([a],[b])=>a.localeCompare(b)).map(([date,value])=>({date,value})),7)}
export function strengthNext(log,low,high){if(!log?.reps?.length)return 'Start with a manageable weight';const reps=log.reps.map(Number);if(reps.every(r=>r>=high))return 'Increase weight slightly next time';if(reps.some(r=>r<low-2))return 'Consider a lighter weight';return 'Keep this weight next time'}
export function normalizeHealthQuest(raw){const source=raw?.state||raw?.data||raw;if(!source||typeof source!=='object'||!source.entries||typeof source.entries!=='object')throw Error('This does not look like a Health Quest export');return Object.entries(source.entries).filter(([d])=>/^\d{4}-\d{2}-\d{2}$/.test(d)).map(([date,e])=>{const meals={};for(const [k] of MEALS){const rawValue=e.mealBehavior?.[k]?.score??(k==='afternoonSnack'&&e.foodModel==='meal-v2'?e.mealBehavior?.snacks?.score:null);if(rawValue==null||rawValue==='')continue;const score=Number(rawValue);if(!Number.isInteger(score)||score<0||score>5)continue;if(k==='nightSnack'){const mapped=({0:0,1:4,2:3,3:2,4:1,5:1})[score];meals[k]=mapped}else if(score!==0){meals[k]=({1:4,2:3,3:2,4:1,5:1})[score]}}return {date,weight:e.weight??e.weightLbs??null,bodyFat:e.bodyFat??null,steps:e.steps??null,activeCalories:e.activeCalories??null,exerciseMinutes:e.exerciseMinutes??null,foodModel:e.foodModel??null,scoringVersion:e.scoringModelVersion??null,meals}})}
export async function importHealthQuest(state,raw){const normalized=normalizeHealthQuest(raw);const source=raw?.state||raw?.data||raw;const strengthSessions=Array.isArray(source.strengthHistory)?source.strengthHistory.filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x.date||'')).map(x=>({date:x.date,completed:Boolean(x.completed),workoutName:x.workoutName||x.workoutId||'Strength session',durationMinutes:Number(x.durationMinutes)||null})):[];const strengthLogs=Array.isArray(source.strengthLogs)?source.strengthLogs.filter(x=>x.date&&x.exercise).map(x=>({date:x.date,exercise:x.exercise,sets:Array.isArray(x.sets)?x.sets:[],note:x.notes||''})):[];const bytes=new TextEncoder().encode(JSON.stringify(raw));const digest=await crypto.subtle.digest('SHA-256',bytes);const hash=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');if(state.importedHealthQuestData[hash])return {duplicate:true,count:0};state.importedHealthQuestData[hash]={importedAt:new Date().toISOString(),raw,normalized,strengthSessions,strengthLogs};return {duplicate:false,count:normalized.length}}
export function seeded(seed){let x=seed>>>0;return()=>{x=(Math.imul(1664525,x)+1013904223)>>>0;return x/4294967296}}
export function simulate(game,state){const seed=[...game.id].reduce((a,c)=>Math.imul(a,31)+c.charCodeAt(0)|0,17)>>>0,rand=seeded(seed),r=readiness(state,game.date),a=attributes(state,game.date),strength=Number(game.strength)||50,home=game.venue==='Home'?3:0,contribution=(r-70)/8+(a.Clutch-50)/15,rawMargin=Math.round((55-strength)/5+home+contribution+(rand()-.5)*25),margin=rawMargin===0?1:rawMargin,win=margin>0;let stats,score;if(game.sport==='football'){const us=17+Math.floor(rand()*22),them=Math.max(3,us-margin);score={us,them};stats={tackles:Math.max(0,Math.round(3+rand()*5+(r-65)/18)),solo:Math.round(2+rand()*3),breakups:Math.round(rand()*3+(r-65)/35),interceptions:rand()<.12+(r/500)?1:0,targets:Math.round(3+rand()*4),completionsAllowed:Math.round(rand()*4),yardsAllowed:Math.round(rand()*55),forcedFumbles:rand()<.09?1:0,snaps:Math.round(48+rand()*20)}}else{const us=58+Math.floor(rand()*38),them=Math.max(30,us-margin);score={us,them};stats={points:Math.round(10+rand()*18+(r-70)/9),assists:Math.round(3+rand()*7),rebounds:Math.round(1+rand()*6),steals:Math.round(rand()*4),turnovers:Math.round(rand()*4),fgPct:Math.round(37+rand()*21),threePct:Math.round(28+rand()*20),minutes:Math.round(27+rand()*10)}}return {sport:game.sport,gameId:game.id,seed,readiness:r,attributes:a,modifiers:{opponentStrength:strength,homeAdvantage:home,userContribution:contribution,variance:margin-((55-strength)/5+home+contribution)},score,stats,win,recap:win?'A composed finish gave the team the edge.':'A close contest leaves useful film for the next one.',simulatedAt:new Date().toISOString()}}
export function signalCount(n){return n<14?'Building scouting report':n<30?'Early signal':n<60?'Developing signal':'Established pattern'}
