import {PROGRAM,weekKey} from './core.js';

const ALIASES={'cable lateral raise':'lateral raise','cable curl':'curls','dumbbell curl':'curls','machine chest press':'chest press','dumbbell chest press':'chest press','dumbbell bench press':'chest press','seated row':'seated cable row','incline db press':'incline dumbbell press','rdl':'romanian deadlift','dead bugs':'dead bug','glute bridges':'hip thrust or glute bridge','farmer carry / suitcase carry':'farmer carry'};
export const canonicalExercise=name=>ALIASES[String(name||'').trim().toLowerCase()]||String(name||'').trim().toLowerCase();
export const exerciseId=name=>canonicalExercise(name).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const draftKey=(date,type,id)=>`${date}|${type}|${id}`;
export function ensureStrengthState(state){state.settings??={};state.settings.program??=structuredClone(PROGRAM);for(const type of ['blue','maize','home'])state.settings.program[type]??=structuredClone(PROGRAM[type]);state.settings.program.white??=structuredClone(PROGRAM.white);for(const item of state.settings.program.blue){if(item[0]==='Cable lateral raise'||item[0]==='Cable Lateral Raise'){item[0]='Lateral Raise';item[2]='dumbbells default; cable or machine okay'}if(item[0]==='Cable curl'||item[0]==='Cable Curl'){item[0]='Curls';item[2]='dumbbells, cable, EZ bar, or machine'}}state.strengthDrafts??={};state.personalRecords??=[];state.strengthLogs??=[];return state}
export function parseTarget(text){const match=String(text).match(/(\d+)\s*×\s*(\d+)(?:\s*[–-]\s*(\d+))?/);return {sets:match?Number(match[1]):3,min:match?Number(match[2]):8,max:match?Number(match[3]||match[2]):12,timed:/seconds|sec/i.test(text)}}
function numeric(value){return value===''||value==null?null:Number.isFinite(Number(value))?Number(value):null}
export function normalizeStrengthLog(raw,source='native'){const name=raw.exerciseName||raw.exercise;if(!raw.date||!name)return null;const sets=Array.isArray(raw.sets)?raw.sets.map(set=>({weight:numeric(set.weight),reps:numeric(set.reps)})):Array.isArray(raw.reps)?raw.reps.map(reps=>({weight:numeric(raw.weight),reps:numeric(reps)})):[];return {id:raw.id||null,date:raw.date,exerciseId:raw.exerciseId||exerciseId(name),exerciseName:name,workoutType:raw.workoutType||null,sets:sets.filter(set=>set.reps!==null||set.weight!==null),progressRequested:raw.progressRequested===undefined?null:raw.progressRequested,isPR:Boolean(raw.isPR),prType:raw.prType||null,prTypes:Array.isArray(raw.prTypes)?raw.prTypes:raw.prType?[raw.prType]:[],source,note:raw.note||raw.notes||''}}
export function exerciseHistory(state,name,{beforeDate=null}={}){const target=canonicalExercise(name),byKey=new Map();for(const batch of Object.values(state.importedHealthQuestData||{}))for(const raw of batch.strengthLogs||[]){const log=normalizeStrengthLog(raw,'Health Quest');if(log&&canonicalExercise(log.exerciseName)===target&&(!beforeDate||log.date<beforeDate))byKey.set(`${log.date}|${target}|${JSON.stringify(log.sets)}`,log)}for(const raw of state.strengthLogs||[]){const log=normalizeStrengthLog(raw);if(log&&canonicalExercise(log.exerciseName)===target&&(!beforeDate||log.date<beforeDate)){for(const key of byKey.keys())if(key.startsWith(`${log.date}|${target}|`))byKey.delete(key);byKey.set(`${log.date}|${target}|${log.id||JSON.stringify(log.sets)}`,log)}}return [...byKey.values()].sort((a,b)=>b.date.localeCompare(a.date))}
export function lastExercise(state,name,day){return exerciseHistory(state,name,{beforeDate:day})[0]||null}
export const totalReps=log=>(log?.sets||[]).reduce((sum,set)=>sum+(Number(set.reps)||0),0);
export const trainingVolume=log=>(log?.sets||[]).reduce((sum,set)=>sum+(Number(set.reps)||0)*(Number(set.weight)||0),0);
export const maxWeight=log=>Math.max(0,...(log?.sets||[]).map(set=>Number(set.weight)||0));
export function formatSets(log){if(!log?.sets?.length)return 'No history yet';const sets=log.sets.filter(set=>set.reps!==null);if(!sets.length)return 'No history yet';const weights=sets.map(set=>set.weight??0),same=weights.every(w=>w===weights[0]);return same?`${weights[0]?`${weights[0]} lb · `:''}${sets.map(set=>set.reps).join(' / ')}${weights[0]?' reps':' reps'}`:sets.map(set=>`${set.weight??0} × ${set.reps}`).join(' · ')}
export function recommendProgression(last,targetText,{increment=5}={}){const target=parseTarget(targetText);if(!last?.sets?.length)return {kind:'start',weight:null,text:'Choose a manageable starting weight.'};const weights=last.sets.map(set=>Number(set.weight)||0),weight=maxWeight(last),reps=last.sets.map(set=>Number(set.reps)||0),allAtTop=reps.length>=target.sets&&reps.slice(0,target.sets).every(rep=>rep>=target.max),sameLoad=weights.every(value=>value===weights[0]);if(reps.some(rep=>rep<Math.max(1,target.min-2)))return {kind:'caution',weight,text:'Consider staying here or reducing slightly. Keep clean form.'};if(last.progressRequested===true&&allAtTop&&sameLoad&&weight>0)return {kind:'weight',weight:weight+increment,text:`Try ${weight+increment} lb for ${target.min}–${target.max} reps.`};if(last.progressRequested===true)return {kind:'reps',weight,text:`Keep ${weight?`${weight} lb`:'this variation'} and beat ${reps.join(' / ')} with clean form.`};return {kind:'repeat',weight,text:`Repeat ${weight?`${weight} lb`:'the previous variation'}; progress only when ready.`}}
export function toggleProgressRequest(state,date,type,name){ensureStrengthState(state);const key=draftKey(date,type,exerciseId(name));const draft=state.strengthDrafts[key]||{};draft.progressRequested=draft.progressRequested===true?false:true;state.strengthDrafts[key]=draft;return draft.progressRequested}
export function updateStrengthDraft(state,date,type,name,patch){ensureStrengthState(state);const key=draftKey(date,type,exerciseId(name));state.strengthDrafts[key]={...(state.strengthDrafts[key]||{}),...patch};return state.strengthDrafts[key]}
export function detectPR(current,history){if(!history.length||!current.sets.length)return [];const priorWeight=Math.max(...history.map(maxWeight)),currentWeight=maxWeight(current),priorVolume=Math.max(...history.map(trainingVolume)),volume=trainingVolume(current),sameWeightHistory=history.filter(log=>maxWeight(log)===currentWeight),bestReps=sameWeightHistory.length?Math.max(...sameWeightHistory.map(totalReps)):null,types=[];if(currentWeight>priorWeight)types.push('weight');if(bestReps!==null&&totalReps(current)>bestReps)types.push('reps');if(volume>priorVolume&&volume>0)types.push('volume');return types}
export function completeWorkout(state,date,type){ensureStrengthState(state);const program=state.settings.program[type]||[];const saved=[];let workingSets=0;for(const [name,targetText] of program){const id=exerciseId(name),key=draftKey(date,type,id),draft=state.strengthDrafts[key];if(!draft)continue;const target=parseTarget(targetText),sets=(draft.sets||[]).map(set=>({weight:numeric(set.weight),reps:numeric(set.reps)})).filter(set=>set.reps!==null&&set.reps>0);if(!sets.length)continue;const logId=`${date}:${type}:${id}`,history=exerciseHistory(state,name,{beforeDate:date}),last=history[0]||null,prTypes=detectPR({sets},history),log={id:logId,date,exerciseId:id,exerciseName:name,exercise:name,workoutType:type,sets,targetSets:target.sets,targetRepMin:target.min,targetRepMax:target.max,progressRequested:draft.progressRequested??null,progressRecommendation:recommendProgression({sets,progressRequested:draft.progressRequested},targetText),previousPerformance:last?{date:last.date,sets:last.sets}:null,isPR:prTypes.length>0,prType:prTypes[0]||null,prTypes,note:draft.note||''};const index=state.strengthLogs.findIndex(item=>item.id===logId);if(index>=0)state.strengthLogs[index]=log;else state.strengthLogs.push(log);workingSets+=sets.length;saved.push(log);delete state.strengthDrafts[key]}state.workouts[date]=type;state.personalRecords=state.personalRecords.filter(record=>!saved.some(log=>log.id===record.logId));for(const log of saved)for(const prType of log.prTypes)state.personalRecords.push({logId:log.id,date,exerciseId:log.exerciseId,exerciseName:log.exerciseName,prType});return {type,exercises:saved.length,workingSets,progressRequested:saved.filter(log=>log.progressRequested).length,prs:saved.filter(log=>log.isPR),logs:saved,xp:type==='white'?25:['home','home-blue','home-maize'].includes(type)?50:75}}
export function weeklyProgressionCount(state,day){const week=weekKey(day);return (state.strengthLogs||[]).filter(log=>weekKey(log.date)===week&&log.progressRequested===true).length}
