import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,PROGRAM,weeklyStrength,readiness,dayXP} from './core.js';
import {ensureStrengthState,exerciseHistory,lastExercise,formatSets,recommendProgression,toggleProgressRequest,updateStrengthDraft,completeWorkout,detectPR} from './strength.js';

test('old programs receive White and generic Blue names without losing custom moves',()=>{const state=initialState();delete state.settings.program.white;state.settings.program.blue[3][0]='Cable lateral raise';state.settings.program.blue[4][0]='Cable curl';state.settings.program.blue[0][0]='My custom press';ensureStrengthState(state);assert.equal(state.settings.program.blue[0][0],'My custom press');assert.equal(state.settings.program.blue[3][0],'Lateral Raise');assert.equal(state.settings.program.blue[4][0],'Curls');assert.deepEqual(state.settings.program.white,PROGRAM.white)});
test('Blue and Maize are the entire core target; White earns only a small bonus',()=>{const state=initialState();state.workouts['2026-10-05']='blue';state.workouts['2026-10-06']='maize';const core=weeklyStrength(state,'2026-10-06'),score=readiness(state,'2026-10-06');assert.equal(core.complete,true);assert.equal(core.bonus,false);state.workouts['2026-10-07']='white';const bonus=weeklyStrength(state,'2026-10-07');assert.equal(bonus.complete,true);assert.equal(bonus.bonus,true);assert.equal(readiness(state,'2026-10-06'),score);assert.equal(dayXP(state,'2026-10-07'),25)});
test('legacy logs remain readable, with different weights shown per set',()=>{const state=initialState();state.strengthLogs.push({date:'2026-09-29',exercise:'Cable lateral raise',weight:20,reps:[12,11,10]});state.strengthLogs.push({date:'2026-10-01',exercise:'Lateral Raise',sets:[{weight:30,reps:10},{weight:30,reps:9},{weight:27.5,reps:9}]});const last=lastExercise(state,'Lateral Raise','2026-10-06');assert.equal(last.date,'2026-10-01');assert.match(formatSets(last),/27.5 × 9/);assert.equal(exerciseHistory(state,'Lateral Raise').length,2);assert.equal(exerciseHistory(state,'Lateral Raise')[1].progressRequested,null)});
test('progress request toggles and persists on the completed exercise',()=>{const state=initialState();assert.equal(toggleProgressRequest(state,'2026-10-06','blue','Chest press'),true);assert.equal(toggleProgressRequest(state,'2026-10-06','blue','Chest press'),false);assert.equal(toggleProgressRequest(state,'2026-10-06','blue','Chest press'),true);updateStrengthDraft(state,'2026-10-06','blue','Chest press',{sets:[{weight:70,reps:12},{weight:70,reps:11},{weight:70,reps:10}]});const summary=completeWorkout(state,'2026-10-06','blue');assert.equal(summary.logs[0].progressRequested,true);assert.equal(summary.progressRequested,1);assert.equal(state.strengthDrafts['2026-10-06|blue|chest-press'],undefined);assert.equal(lastExercise(state,'Chest press','2026-10-07').progressRequested,true)});
test('double progression chooses reps, then weight, and never increases without +',()=>{const sets=[{weight:70,reps:12},{weight:70,reps:11},{weight:70,reps:10}],target='3 × 8–12';assert.equal(recommendProgression({sets,progressRequested:true},target).kind,'reps');assert.equal(recommendProgression({sets:[{weight:70,reps:12},{weight:70,reps:12},{weight:70,reps:12}],progressRequested:true},target).weight,75);assert.equal(recommendProgression({sets:[{weight:70,reps:12},{weight:70,reps:12},{weight:70,reps:12}],progressRequested:null},target).kind,'repeat');assert.equal(recommendProgression({sets:[{weight:70,reps:5},{weight:70,reps:6},{weight:70,reps:5}],progressRequested:true},target).kind,'caution')});
test('personal records are based on prior logs and same-day completion is an upsert',()=>{const state=initialState();state.strengthLogs.push({date:'2026-09-29',exercise:'Chest press',weight:70,reps:[10,9,8]});updateStrengthDraft(state,'2026-10-06','blue','Chest press',{sets:[{weight:75,reps:8},{weight:75,reps:8},{weight:75,reps:8}]});let result=completeWorkout(state,'2026-10-06','blue');assert.equal(result.prs.length,1);assert.ok(result.prs[0].prTypes.includes('weight'));assert.ok(state.personalRecords.length>0);result=completeWorkout(state,'2026-10-06','blue');assert.equal(state.strengthLogs.filter(log=>log.id==='2026-10-06:blue:chest-press').length,1);assert.equal(result.logs.length,0);assert.deepEqual(detectPR({sets:[{weight:70,reps:10}]},[]),[])});
